# Generated by Django 3.2.23 on 2024-02-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
