# Generated by Django 3.2.23 on 2024-02-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0004_rename_special_day_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
