# Generated by Django 3.2.23 on 2024-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBooks', '0005_product_prev_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prev_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
